filegroup(
    name = "cpp2_files",
    srcs = glob(["**/*.cpp2"]),
    visibility = ["//visibility:public"],
)

# filegroup(
#     name = "cpp2_files",
#     srcs = glob(["**/curr_test.cpp2"]),
#     visibility = ["//visibility:public"],
# )