# filegroup(
#     name = "cpp2_files",
#     srcs = glob(["**/*.cpp2"]),
#     visibility = ["//visibility:public"],
# )

filegroup(
    name = "cpp2_files",
    srcs = glob(["**/mixed-bounds-safety-with-assert-2.cpp2"]),
    visibility = ["//visibility:public"],
)